name = "alger-music-adapter"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
METING_API_URL = "https://meting-api.your-domain.workers.dev"
METING_TOKEN = "token"
